### ISSUE TITLE
Error when open Atom and PDF was open before

### ISSUE THREAD

**Issue by piclemx** [izuzak/atom-pdf-view#134]
When I have a pdf open with atom. The next time, I open atom I got this error

```
Error: Cannot find module '/home/alexandre/.atom/packages/pdf-view/deserialize'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.atom.deserializers.add.deserialize [as deserialize] (/usr/share/atom/resources/app.asar/src/package.js:454:41)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
    at /usr/share/atom/resources/app.asar/src/pane.js:34:30
    at Array.map (native)
    at Function.module.exports.Pane.deserialize (/usr/share/atom/resources/app.asar/src/pane.js:33:35)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
    at /usr/share/atom/resources/app.asar/src/pane-axis.js:25:30
    at Array.map (native)
    at Function.module.exports.PaneAxis.deserialize (/usr/share/atom/resources/app.asar/src/pane-axis.js:24:39)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
    at PaneContainer.module.exports.PaneContainer.deserialize (/usr/share/atom/resources/app.asar/src/pane-container.js:64:40)
    at Workspace.module.exports.Workspace.deserialize (/usr/share/atom/resources/app.asar/src/workspace.js:153:33)
    at AtomEnvironment.module.exports.AtomEnvironment.loadStateSync (/usr/share/atom/resources/app.asar/src/atom-environment.js:940:24)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:685:12)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)handleSetupError @ index.js:62
```

**Comment by piclemx** [comment]
![image](https://cloud.githubusercontent.com/assets/14060997/14505510/795f1c90-0187-11e6-8a3c-2be2586355c9.png)

**Comment by izuzak** [comment]
Hi @piclemx 👋 

Which OS + version are you using, which version of Atom, and which version of the pdf-view package?

**Comment by piclemx** [comment]
Hi @izuzak ,

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Atom version : 1.4.2

In packages.json pdf-view version = 0.50.0

**Comment by izuzak** [comment]
Thanks, @piclemx. Do you see the same problem if you upgrade to the latest stable version of Atom? Version 1.4.2, which is what you're using, is a bit old.

**Comment by piclemx** [comment]
Thanks @izuzak , that solve de problem sorry :P
