### ISSUE TITLE
Uncaught ReferenceError: closeOnError is not defined

### ISSUE THREAD

**Issue by ConnorBaker** [izuzak/atom-pdf-view#168]
This is a fresh build of atom.

1. Open any PDF file via atom

**Atom**: 1.16.0-dev-02a1010a7 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package 0.54.0

### Stack Trace

Uncaught ReferenceError: closeOnError is not defined

```
At /Users/connorbaker/.atom/packages/pdf-view/lib/pdf-editor-view.js:40

ReferenceError: closeOnError is not defined
    at PdfEditorView (pdf-editor-view.js:40:20)
    at openUri (pdf-editor.js:57:12)
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at TreeView.module.exports.TreeView.fileViewEntryClicked (/app.asar/node_modules/tree-view/lib/tree-view.js:486:40)
    at TreeView.module.exports.TreeView.entryClicked (/app.asar/node_modules/tree-view/lib/tree-view.js:474:14)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:190:26)
    at /app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at /app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:17.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-monokai.theme-one-dark-ui)
     -1:17.5.0 application:open (input.hidden-input)
     -1:15.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-monokai.theme-one-dark-ui)
     -1:12.9.0 core:close (input.hidden-input)
     -1:12.2.0 settings-view:open (input.hidden-input)
     -0:59 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.3 
atom-monokai 0.10.9 
file-icons 2.0.15 
intentions 1.1.2 
language-latex 1.0.0 
language-mips 0.3.0 
latex 0.42.3 
linter 1.11.23 
linter-gcc 0.7.1 
linter-spell 0.12.6 
linter-spell-latex 0.9.1 
minimap 4.26.8 
pdf-view 0.54.0 
platformio-ide-terminal 2.2.3 
```

**Comment by izuzak** [comment]
Thanks for reporting this. I _think_ this should be fixed in the new version of the package. Mind giving it a try and letting me know if it still throws an error? 🙏

**Comment by ConnorBaker** [comment]
It's fixed! Thank you for the exceptionally quick update!
