### ISSUE TITLE
Uncaught Error: Requesting object that isn't resolved yet Arial_path_(

### ISSUE THREAD

**Issue by Josh-ES** [izuzak/atom-pdf-view#171]
[Enter steps to reproduce:]

1. Compile a report written using LaTeX.
2. Second PDF imported in the report as an appendix, using pdfpages.
3. Attempt to open PDF in Atom using pdf-view.
4. Page missing from imported PDF.

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package 0.55.0

### Stack Trace

Uncaught Error: Requesting object that isn't resolved yet Arial_path_(

```
At /Users/joshua/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:287

Error: Requesting object that isn't resolved yet Arial_path_(
    at error (/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:287:15)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:10109:15)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:2961:31)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:7681:32)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:7829:24)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:7148:28)
    at /packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:10283:45)
```

### Commands

```
     -6:24 core:save (input.hidden-input)
     -3:49.7.0 core:close (div.pdf-view)
     -3:46 core:save (input.hidden-input)
  2x -1:55.2.0 core:backspace (input.hidden-input)
     -1:53.4.0 core:save (input.hidden-input)
     -1:17 core:backspace (input.hidden-input)
     -1:16.4.0 core:save (input.hidden-input)
  2x -1:15 core:close (input.hidden-input)
     -1:10.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
emmet 2.4.3 
git-plus 7.3.3 
goto-definition 1.2.0 
intellij-idea-keymap 0.2.3 
jump-to-import 2.1.1 
language-babel 2.55.6 
language-docker 1.1.7 
language-latex 1.0.0 
language-matlab 0.2.1 
language-r 0.4.1 
language-scala 1.1.8 
language-typescript-grammars-only 1.6.0 
latex 0.42.3 
linter 1.11.23 
pdf-view 0.55.0 
print-atom 0.1.1 
react 0.16.2 
react-snippets 0.7.0 
remote-atom 1.3.10 
svg-preview 0.11.0 
```

**Comment by izuzak** [comment]
Thanks for opening an issue, @Josh-ES :bow:. The stack trace indicates that the exception is being thrown from pdf.js -- the dependency this Atom package uses to render PDFs. I won't have time to look into why this is happening anytime soon (and if there's anything there can be done about the problem in this package, or if it needs to be handled in pdf.js), but if someone else wants to dig in -- I'd be happy to review a pull request.

**Comment by AllSeeingEye** [comment]
Possibly a duplicate of #4244.
