### ISSUE TITLE
Cannot install（code Z_BUF_ERROR）

### ISSUE THREAD

**Issue by RabbitTiBi** [izuzak/atom-pdf-view#219]
Since the installation process is fully automated, I don't know where the problem is, but I got such feedback:
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\.atom\.apm\_logs\2019-01-29T00_14_31_087Z-debug.log

The complete error file content is：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\DELL\\AppData\\Local\\atom\\app-1.35.0-beta0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\DELL\\AppData\\Local\\atom\\app-1.35.0-beta0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\DELL\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\DELL\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/pdf-view/versions/0.71.0/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.16',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=ia32',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 926405625db82c7e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/pdf-view/versions/0.71.0/tarball 6674ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/pdf-view/versions/0.71.0/tarball fetched in 6737ms
9 timing stage:loadCurrentTree Completed in 7257ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule pdf-view@0.71.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/loophole 1303ms (from cache)
18 silly pacote version manifest for loophole@1.1.0 fetched in 1305ms
19 silly resolveWithNewModule loophole@1.1.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/fs-plus 1309ms (from cache)
21 silly pacote range manifest for fs-plus@2.x fetched in 1313ms
22 silly resolveWithNewModule fs-plus@2.10.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/underscore-plus 5705ms (from cache)
24 silly pacote range manifest for underscore-plus@^1.6 fetched in 5706ms
25 silly resolveWithNewModule underscore-plus@1.6.8 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 8856ms (from cache)
27 silly pacote range manifest for atom-space-pen-views@^2.0.3 fetched in 8859ms
28 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/pdfjs-dist 9232ms (from cache)
30 http fetch GET 200 https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-1.9.426.tgz 86ms (from cache)
31 silly fetchPackageMetaData error for pdfjs-dist@1.9.426 zlib: unexpected end of file
32 http fetch GET 304 https://registry.npmjs.org/node-ensure 26185ms attempt #2 (from cache)
33 silly pacote version manifest for node-ensure@0.0.0 fetched in 26186ms
34 silly resolveWithNewModule node-ensure@0.0.0 checking installable status
35 timing stage:rollbackFailedOptional Completed in 1ms
36 timing stage:runTopLevelLifecycles Completed in 33467ms
37 silly saveTree apm-install-dir-119029-23128-1nwne65.2fwy
37 silly saveTree `-- pdf-view@0.71.0
37 silly saveTree   +-- atom-space-pen-views@2.2.0
37 silly saveTree   +-- fs-plus@2.10.1
37 silly saveTree   | `-- underscore-plus@1.6.8
37 silly saveTree   +-- loophole@1.1.0
37 silly saveTree   +-- node-ensure@0.0.0
37 silly saveTree   `-- underscore-plus@1.6.8
38 verbose stack ZlibError: zlib: unexpected end of file
38 verbose stack     at Zlib.(anonymous function).onerror (C:\Users\DELL\AppData\Local\atom\app-1.35.0-beta0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:131:21)
38 verbose stack     at Unzip.write (C:\Users\DELL\AppData\Local\atom\app-1.35.0-beta0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:255:31)
38 verbose stack     at Unzip.flush (C:\Users\DELL\AppData\Local\atom\app-1.35.0-beta0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:222:10)
38 verbose stack     at Unzip.end (C:\Users\DELL\AppData\Local\atom\app-1.35.0-beta0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:229:10)
38 verbose stack     at Object.end (C:\Users\DELL\AppData\Local\atom\app-1.35.0-beta0\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:415:21)
38 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
38 verbose stack     at Object.onceWrapper (events.js:313:30)
38 verbose stack     at emitNone (events.js:111:20)
38 verbose stack     at PassThrough.emit (events.js:208:7)
38 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
38 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
38 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
39 verbose cwd C:\Users\DELL\AppData\Local\Temp\apm-install-dir-119029-23128-1nwne65.2fwy
40 verbose Windows_NT 10.0.17134
41 verbose argv "C:\\Users\\DELL\\AppData\\Local\\atom\\app-1.35.0-beta0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\DELL\\AppData\\Local\\atom\\app-1.35.0-beta0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\DELL\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\DELL\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/pdf-view/versions/0.71.0/tarball" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=ia32" "--global-style"
42 verbose node v8.9.3
43 verbose npm  v6.2.0
44 error code Z_BUF_ERROR
45 error errno -5
46 error zlib: unexpected end of file
47 verbose exit [ -5, true ]

How can I solve this problem?

**Comment by tillepprecht** [comment]
I have the same problem, have you found a solution yet?

**Comment by mmikhasenko** [comment]
Same error. Windows 10, Julia 1.1.0
