### ISSUE TITLE
PDF viewer not working with atom V0.166

### ISSUE THREAD

**Issue by dougcoates** [izuzak/atom-pdf-view#43]
I am using atom version 0.166 and the PDF viewer doesn't seem to work, when opening a PDF I get the following error:

``
Uncaught SyntaxError: /home/doug/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26 PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Unexpected token ILLEGAL
``

and the this stack trace:

``
/home/doug/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:451:25)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/doug/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:4:1)
  at Object.<anonymous> (/home/doug/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:61:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at openUri (/home/doug/.atom/packages/pdf-view/lib/pdf-editor.coffee:18:22)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:479:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:412:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
``

**Comment by izuzak** [comment]
This sounds very similar to https://github.com/izuzak/atom-pdf-view/issues/31 -- does the advice in that issue help resolve your problem as well?

**Comment by izuzak** [comment]
Going to close this but let me know if the advice from #31 doesn't help. :cake:
