### ISSUE TITLE
Uncaught SyntaxError: /home/dylan/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by DylanTheVillain** [izuzak/atom-pdf-view#46]
[Enter steps to reproduce below:]

1. ...  Install pdf-view.
2. ...  Try to open a pdf.

**Atom Version**: 0.174.0
**System**: linux 3.16.7.4-1-MANJARO
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.15.0

### Stack Trace

Uncaught SyntaxError: /home/dylan/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected token ILLEGAL

```
At /home/dylan/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26

/home/dylan/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:451:25)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/home/dylan/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:4:1)
  at Object.<anonymous> (/home/dylan/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/usr/share/atom/resources/app/src/coffee-cache.js:65:19)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at openUri (/home/dylan/.atom/packages/pdf-view/lib/pdf-editor.coffee:18:22)
  at wrappedOpener (/usr/share/atom/resources/app/src/workspace.js:562:16)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/tree-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/tree-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
language-latex, v0.4.1
language-rust, v0.3.4
language-x86, v0.1.0
minimap, v3.5.5
pdf-view, v0.15.0
seti-syntax, v0.2.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
This sounds very similar to https://github.com/izuzak/atom-pdf-view/issues/31 -- does the advice in that issue help resolve your problem as well?

**Comment by izuzak** [comment]
Going to close this but let me know if the advice from #31 doesn't help. :cake:
