### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by arynhard** [izuzak/atom-pdf-view#48]
Got this error after:

Updating to Atom 0.177.0 and pdf-view to 0.16.0.
Clicking on pdf file in tree view.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.16.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At /Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) [as .node] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/andrewrynhard/Development/projects/dotfiles/atom/packages/pdf-view/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/andrewrynhard/Development/projects/dotfiles/atom/packages/pdf-view/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/andrewrynhard/Development/projects/dotfiles/atom/packages/pdf-view/lib/pdf-editor-view.coffee:5:10)
  at Object.<anonymous> (/Users/andrewrynhard/Development/projects/dotfiles/atom/packages/pdf-view/lib/pdf-editor-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at openUri (/Users/andrewrynhard/Development/projects/dotfiles/atom/packages/pdf-view/lib/pdf-editor.coffee:18:22)
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:568:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:418:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:671:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:415:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.0
autocomplete-snippets, v1.0.1
coffee-lint, v0.7.3
language-docker, v1.1.2
language-latex, v0.4.1
pdf-view, v0.16.0
script, v2.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
Thanks for the report. Not really sure why that's happening, though -- I'm using the same versions and OS, and was able to install the package just now. 

Can you try uninstalling pdf-view completely and then installing again? Did you install/update pdf-view from Settings View or do you have a local clone of the package and link+install from there? Does installing by running `apm install pdf-view` give the same error?

**Comment by arynhard** [comment]
@izuzak: I removed pdf-view completely and tried updating via the settings but got an error. Unfortunately I already tried your recommendation of using `apm instal pdf-viewl`, which worked, but now I cannot report the error I got. My apologies.

**Comment by izuzak** [comment]
No problem -- thanks for letting me know. And please feel free to leave a comment if this happens again or if you can reproduce it somehow.
