### ISSUE TITLE
Uncaught SyntaxError: /home/diego/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Hotboards** [izuzak/atom-pdf-view#53]
The plugin dosen't work when i try to open a pdf file

**Atom Version**: 0.186.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.17.0

### Stack Trace

Uncaught SyntaxError: /home/diego/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected token ILLEGAL

```
At /home/diego/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26

/home/diego/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/diego/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:4:1)
  at Object.<anonymous> (/home/diego/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:67:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at openUri (/home/diego/.atom/packages/pdf-view/lib/pdf-editor.coffee:18:22)
  at wrappedOpener (/usr/share/atom/resources/app/src/workspace.js:578:16)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:495:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:428:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:710:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

**Comment by gncs** [comment]
A similar issue here:

**Atom Version**: 0.186.0
**System**: linux 3.14.9-200.fc20.x86_64
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.17.0

### Stack Trace

Uncaught SyntaxError: /home/gregor/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /h
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected token ILLEGAL

```
At /home/gregor/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26

/home/gregor/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /h
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/gregor/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:12:3)
    at Object.<anonymous> (/home/gregor/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:340:4)
    at Module._compile (module.js:475:26)
```

### Installed Packages

```coffee
# User
file-icons, v1.5.0
language-latex, v0.4.1
pdf-view, v0.17.0
vim-mode, v0.36.0

# Dev
No dev packages
```

The following code from #31 did not resolve the issue.
```
cd  .atom/packages/pdf-view/
rm -rf node_modules
apm install .
```

**Comment by Hotboards** [comment]
it works!!!!!

with the last code
```
cd  .atom/packages/pdf-view/
rm -rf node_modules
apm install .
```

but before to do that i have to change my python version from my arch linux

```
export PYTHON=/usr/bin/python2
```

**Comment by izuzak** [comment]
Yeah, see https://github.com/izuzak/atom-pdf-view/issues/46 and https://github.com/izuzak/atom-pdf-view/issues/31 for similar reports.

**Comment by Koltharius** [comment]
I use Manjaro and atom 0.190.0, I change my python version to python 2 but the error persist.
Any ideas?

Thanks!
