### ISSUE TITLE
Failed to activate the pdf-view package

### ISSUE THREAD

**Issue by fbbdev** [izuzak/atom-pdf-view#56]
Steps to reproduce:

1. Install atom v.0.190.0
2. Install pdf-view package
3. Run atom in 1.0 API preview mode: `atom -1`

**Atom Version**: 0.190.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.17.0

### Stack Trace

Failed to activate the pdf-view package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/home/fabio/.atom/packages/pdf-view/lib/pdf-editor.coffee:7:19)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:19)
  at /usr/share/atom/resources/app/src/package.js:206:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:199:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:435:21)
  at /usr/share/atom/resources/app/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:302:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:634:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:54:25)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-css, v0.6.0
autocomplete-glsl, v0.2.0
autocomplete-haskell, v0.2.1
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-plus-jedi, v0.0.9
bezier-curve-editor, v0.6.6
color-picker, v1.6.0
fancy-new-file, v0.7.0
format-sql, v0.2.0
git-blame, v0.4.0
git-history, v2.5.0
git-log, v0.3.0
highlight-line, v0.10.1
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-python-pep8, v0.2.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
ogg-preview, v0.2.0
pdf-view, v0.17.0
project-manager, v1.15.5
quick-move-file, v0.7.0
scroll-sync, v0.1.1
svg-preview, v0.5.1
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report -- should be fixed in the new version. Let me know if you can still reproduce this in Atom 0.191.0 and the latest version of this package.

**Comment by fbbdev** [comment]
Ok, it does not happen anymore - tested on 0.192.0
