### ISSUE TITLE
Uncaught SyntaxError: /home/fabio/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by fbbdev** [izuzak/atom-pdf-view#57]
**Atom Version**: 0.190.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.17.0

### Stack Trace

Uncaught SyntaxError: /home/fabio/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected token ILLEGAL

```
At /home/fabio/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26

/home/fabio/.atom/packages/pdf-view/node_modules/pdf.js/build/generic/build/pdf.js:26
PDFJS.build = 'fatal: Not a git repository (or any parent up to mount point /t
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/fabio/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:4:1)
  at Object.<anonymous> (/home/fabio/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at openUri (/home/fabio/.atom/packages/pdf-view/lib/pdf-editor.coffee:18:22)
  at wrappedOpener (/usr/share/atom/resources/app/src/workspace.js:510:18)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:432:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:365:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:710:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -2:21.7 core:confirm (atom-text-editor.editor.mini)
     -2:11.7 core:close (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -2:08.2 find-and-replace:show (atom-text-editor.editor)
     -2:06.3 find-and-replace:focus-next (atom-text-editor.editor.mini)
     -2:00.4 editor:consolidate-selections (atom-text-editor.editor)
     -2:00.4 core:cancel (atom-text-editor.editor)
     -1:59.1 core:save (atom-text-editor.editor)
     -0:57.0 core:select-to-bottom (atom-text-editor.editor)
     -0:56.2 core:paste (atom-text-editor.editor)
     -0:55.1 core:undo (atom-text-editor.editor)
     -0:47.3 core:paste (atom-text-editor.editor)
     -0:45.9 core:save (atom-text-editor.editor)
  2x -0:23.6 core:backspace (atom-text-editor.editor)
     -0:22.2 core:move-up (atom-text-editor.editor)
     -0:22.0 core:move-left (atom-text-editor.editor)
  2x -0:21.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-css, v0.6.0
autocomplete-glsl, v0.2.1
autocomplete-haskell, v0.2.1
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-plus-jedi, v0.0.9
bezier-curve-editor, v0.6.6
color-picker, v1.6.0
git-log, v0.3.0
highlight-line, v0.10.1
language-cmake, v0.1.1
language-d, v3.1.2
language-diff, v0.3.0
language-erlang, v2.0.0
language-gitignore, v0.2.0
language-glsl, v2.0.0
language-haskell, v1.0.0
language-idl, v0.2.0
language-latex, v0.6.0
language-llvm, v0.1.0
language-opencl, v0.1.0
language-qml, v0.1.0
language-r, v0.1.1
language-sln, v0.1.0
language-svg, v0.8.0
language-swig, v0.1.0
language-twig, v1.6.0
language-x86, v0.1.0
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-python-pep8, v0.2.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
ogg-preview, v0.2.0
pdf-view, v0.17.0
project-manager, v1.15.5
quick-move-file, v0.7.0
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by Koltharius** [comment]
I use Manjaro and atom 0.190.0 and I have same isue. I change my python version to python 2 and reinstall the modules but the error persist.
Any ideas?

Thanks!

**Comment by izuzak** [comment]
@fbbdev @Koltharius Can you try the approach described in https://github.com/izuzak/atom-pdf-view/issues/31#issuecomment-63220894 ?

**Comment by Koltharius** [comment]
I try it but the error the error persist =(

**Comment by fbbdev** [comment]
It didn't work for me either
