### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'index.pdf'

### ISSUE THREAD

**Issue by wanghaisheng** [izuzak/atom-pdf-view#58]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.17.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'index.pdf'

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'index.pdf'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at PdfEditorView.module.exports.PdfEditorView.updatePdf (/Users/wanghaisheng/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:159:35)
    at PdfEditorView.module.exports.PdfEditorView.initialize (/Users/wanghaisheng/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:51:12)
    at PdfEditorView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at PdfEditorView.ScrollView (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new PdfEditorView (/Users/wanghaisheng/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:26:50)
```

### Commands

```
     -2:21.3 window:install-shell-commands (atom-text-editor.editor)
     -1:54.7 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -1:45.9 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "seti-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
pdf-view, v0.17.0
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@wanghaisheng Can you share some steps which reproduce this problem?

**Comment by wanghaisheng** [comment]
I just install pdf-view packages into my atom ,try to open one pdf file then came this issue and  I report it using  the hint

**Comment by izuzak** [comment]
@wanghaisheng Does this happen for every pdf file or only some? How did you try to open that PDF file exactly? Having some reproduction steps would be helpful. Thanks!

**Comment by wanghaisheng** [comment]
sorry .when I restart atom and the problem disappear. if  I encounter again ,i will report in more details
