### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by c-benko** [izuzak/atom-pdf-view#61]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.19.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/craigbenko/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:24

TypeError: undefined is not a function
  at PdfEditorView.module.exports.PdfEditorView.initialize (/Users/craigbenko/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:24:17)
  at PdfEditorView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at PdfEditorView.ScrollView (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
  at new PdfEditorView (/Users/craigbenko/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:12:3)
  at openUri (/Users/craigbenko/.atom/packages/pdf-view/lib/pdf-editor.coffee:18:5)
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:578:16)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:495:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:428:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:710:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:427:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:178:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -4:15.1 project-manager:save-project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.9 core:confirm (input.native-key-bindings)
  2x -4:13.9 focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:07.9 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:05.0 core:move-down (atom-text-editor.editor.mini)
     -4:04.3 core:confirm (atom-text-editor.editor.mini)
     -4:04.3 latex:build (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:53.1 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -3:48.7 core:backspace (atom-text-editor.editor.mini)
     -3:43.5 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
     -3:20.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode)
     -3:16.5 core:move-down (atom-text-editor.editor.mini)
     -3:15.8 core:confirm (atom-text-editor.editor.mini)
     -3:15.8 latex:build (atom-text-editor.editor.vim-mode.command-mode)
     -2:25.5 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.9 core:cancel (a.stack-toggle)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-cython, v0.3.0
language-latex, v0.6.1
latex, v0.21.0
linter, v0.12.0
pdf-view, v0.19.0
project-manager, v1.15.5
vim-mode, v0.43.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Try updating Atom to 0.191.0, that should fix the problem.

**Comment by c-benko** [comment]
Great, all is good now. Thanks.
