### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/ivan/latex/cubawiki/AED3-Apunte-sa...

### ISSUE THREAD

**Issue by FlyingPumba** [izuzak/atom-pdf-view#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.22.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/ivan/latex/cubawiki/AED3-Apunte-sacamacho/apunte.pdf'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/home/ivan/latex/cubawiki/AED3-Apunte-sacamacho/apunte.pdf'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at PdfEditorView.module.exports.PdfEditorView.updatePdf (/home/ivan/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:155:35)
    at /home/ivan/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:61:26
    at later (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:724:25)
```

### Commands

```
     -2:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:07.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:07.6.0 core:paste (atom-text-editor.editor.is-focused)
     -2:07.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:47.4.0 latex:build (atom-text-editor.editor.is-focused)
     -0:36.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:35.1.0 latex:build (atom-text-editor.editor.is-focused)
     -0:27 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.2.0 latex:build (atom-text-editor.editor.is-focused)
     -0:22.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.5.0 latex:build (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "latexer"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-type-icons, v0.7.0
language-latex, v0.6.1
language-x86asm, v0.5.1
latex, v0.24.2
pdf-view, v0.22.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Can you share some steps which reproduce this problem, @FlyingPumba, or any other details about what you were doing to trigger this?

**Comment by FlyingPumba** [comment]
@izuzak Not much details on how to reproduce it: I was working with Latex files, and had the compiled pdf opened with the pdf-view package. Then I re-compiled the project, and got an error, which I suppose that left the pdf file half way completed.
