### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kretes** [izuzak/atom-pdf-view#89]
[Enter steps to reproduce below:]

1. instaled this addon
2. tried to open a pdf from the project (didn't restart atom upfront)

**Atom Version**: 0.175.0
**System**: linux 3.19.0-30-generic
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.30.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/tomasz/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:24

TypeError: undefined is not a function
  at PdfEditorView.module.exports.PdfEditorView.initialize (/home/tomasz/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:24:17)
  at PdfEditorView.View (/usr/share/atom/resources/app/node_modules/encoding-selector/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at PdfEditorView.ScrollView (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
  at new PdfEditorView (/home/tomasz/.atom/packages/pdf-view/lib/pdf-editor-view.coffee:12:3)
  at openUri (/home/tomasz/.atom/packages/pdf-view/lib/pdf-editor.coffee:19:9)
  at wrappedOpener (/usr/share/atom/resources/app/src/workspace.js:568:16)
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app/src/workspace.js:485:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:418:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/usr/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/encoding-selector/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app/node_modules/encoding-selector/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -1:47.4 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:45.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:45.5 core:cancel (atom-text-editor.editor.mini)
     -1:45.3 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:44.9 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:43.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:43.9 core:cancel (atom-text-editor.editor.mini)
     -1:43.5 command-palette:toggle (atom-pane.pane.active)
  5x -1:39.8 core:backspace (atom-text-editor.editor.mini)
     -1:33.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:33.0 core:cancel (atom-text-editor.editor.mini)
     -1:32.4 settings-view:open (atom-pane.pane.active)
 24x -1:03.7 core:backspace (atom-text-editor.editor.mini)
     -0:19.2 core:confirm (atom-text-editor.editor.mini)
  3x -0:03.9 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
pdf-view, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
You're on a super old version of Atom -- try upgrading to Atom 1.0.19, that should fix things.

https://github.com/atom/atom/releases
